spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://192.168.2.9:3306/my-paste-bin
    username: azin
  application:
    name: PasteBin
  flyway:
    enabled: true
    locations: classpath:db/migration
  mvc:
    log-request-details: true
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
management:
  endpoints:
    web:
      cors:
        allowed-origins: '*'
