spring.datasource.type=com.zaxxer.hikari.HikariDataSource
spring.datasource.url=jdbc:mysql://192.168.2.9:3306/my-paste-bin
spring.datasource.username=azin
spring.application.name=PasteBin
spring.flyway.locations=classpath:db/migration
mybatis-plus.mapper-locations=classpath:/mapper/*.xml
mybatis-plus.global-config.db-config.logic-delete-value=1
mybatis-plus.global-config.db-config.logic-not-delete-value=0
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
management.endpoints.web.cors.allowed-origins=*
spring.task.execution.pool.core-size=5
spring.task.execution.pool.max-size=10
spring.task.execution.pool.queue-capacity=25
spring.task.execution.pool.keep-alive=60s
spring.task.execution.thread-name-prefix=executor-
################################ Casdoor ############################
casdoor.endpoint=https://auth.azin.cc
casdoor.certificate=-----BEGIN CERTIFICATE-----\
MIIE3TCCAsWgAwIBAgIDAeJAMA0GCSqGSIb3DQEBCwUAMCgxDjAMBgNVBAoTBWFk\
bWluMRYwFAYDVQQDEw1jZXJ0LWJ1aWx0LWluMB4XDTI1MDEwNDA3MjkzNFoXDTQ1\
MDEwNDA3MjkzNFowKDEOMAwGA1UEChMFYWRtaW4xFjAUBgNVBAMTDWNlcnQtYnVp\
bHQtaW4wggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQC261XnwpPPoksk\
8aGX6tQ58l6lfL1cljhXWszj2vWRnXBkDO+GxfQau3zBAijpWrHgta9iCNB4RwtO\
RdL8Qa4HS6imny+FJecc6hzR0UBC3BhiYyKVNOe5mXS75XLvx3VOCKgW/C8Psc2x\
t6N8JAER0d4tHbo8ZqjD2EzavWpzRP1h7bkV/Wi3K5Yui9Tn9WxJDdEiQ3ZDMs8D\
Y4acA+2VvfbCF9WHQjsAbJ075KcHjCZl5i3HcMa/ykv0QiCPQbRhIGfAPxiJBdtN\
4rqx9JRT28oqgrEB3BeAGptYNfXJ383HoDI5dWU8/dRH4bYKnIj8/iSApiP2qpfd\
55jb91uroWpPXgCciH97jZP45FDT5bd1pQQih6wAdVpYPtpwrUlJMjcbcQ104JuJ\
GuKmviIAL6rLMv2lT5j5BIJKtSqO4X5kuolU2BjIadnpJO+FVS/07t5uv8vLvYtS\
I75QbpByNoace8g3CG+tPDCXuQJyyud8yM1g23ouCYdtEjL+JuJUnjzgV54F38W5\
L5n3pBfkXSqsv4EN5zNgf2b1gg2gUFIiZcD2QJuQXGOt/DRmpgZdUwVXZMbKPHlF\
LRPXoexmFsb3RXR0RZgKOJfSKv1nV9Mb0KnQWROEQ5+s7JfxaSebUrvU3EpVhi5w\
ys1UjFTOkU0NlBReWZH7IGQhQN5vIwIDAQABoxAwDjAMBgNVHRMBAf8EAjAAMA0G\
CSqGSIb3DQEBCwUAA4ICAQCIjsHJ3ojO9KgH9xhuKPa/KlFkj0trzAgtnN+IMFHb\
z5of7UunspOKqncwgiOc2BH6L+hOHKNKcmqBejYmXrXP87B05MNbJf/7bJ6TU3Hz\
saslohajSVI9sNptGIZ6ZoLU3MqgtlDU6xGpentFyghmb3UJXN/DtT2rYkGKnsZm\
AOpkVaQ8k8TkIsfX6DQZVsF5wXUu/kbAYEVwbqL/okvsD81IUPUIsTHtC6j41caA\
ROPhOBnn+pZriiizlpMRFtsEt9rrkI9kXIk/UqLi0qWqAhVZo6LSX5A4US9vB9Oj\
2tlFK+YY4AA+cek61XWCnw1aZmSZ91Y1qF+u39n4DFHDx4Pmse7pwUHkXQLmfyV0\
agXYdPYkIbUe/SuXaqZUw2WvbCQrlXUNHkdhurGAb3SLrkUNP05Cby3TEtDcvWed\
1mTVEZ4YN0OxlXc1UKNuAADMOHdDcYrZoZ0ZUddfHxN4Ux/JMH1qBGsmEwjgfPp1\
1sO4u1rzKRF/K1uFPQKqBpBl++L46wY0KgdyYUTOr0R316RuMHMPkQKwLhj0cM8w\
TC6ZxbHtn0T2ARpQPraroKf7GKKNv/ECPH7zxGnptJi1lf8sNvtWXYOwR8vbQTqs\
yO6GdxYvxfamWXPfpTuqETsGQ9OuVqPeH7TTNTkP4HRenMirt9bpS16pZucQ8iDP\
6Q==\
-----END CERTIFICATE-----

