# 创建todo表格Flyway插件MySQL脚本
CREATE TABLE IF NOT EXISTS `todo_table`
(
    id           INT PRIMARY KEY AUTO_INCREMENT COMMENT '自增ID',
    content      TEXT        NOT NULL COMMENT 'Todo内容',
    created_time TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_time TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    due_date     TIMESTAMP   NOT NULL COMMENT '过期时间',
    deleted      TINYINT(1)  NOT NULL DEFAULT 0,
    user_id      VARCHAR(64) NOT NULL,
    status       VARCHAR(64) NOT NULL DEFAULT 0 COMMENT '状态 ACTIVE为激活中 DISABLED为已禁用 DELETE为已删除'
);